"""Stable machine-readable replay decision reason codes."""

from __future__ import annotations

from enum import Enum


class ReplayReasonCode(str, Enum):
    """Stable reason codes for fail-closed replay decisions.

    These codes are intended for integration logic, metrics, and operator logs.
    Human-readable exception messages may change; these values should remain
    stable across compatible RouteForge releases.
    """

    # Level / capability gates.
    UNSUPPORTED_REPLAY_LEVEL = "UNSUPPORTED_REPLAY_LEVEL"
    BACKEND_LEVEL_NOT_SUPPORTED = "BACKEND_LEVEL_NOT_SUPPORTED"
    INDEX_DTYPE_NOT_SUPPORTED = "INDEX_DTYPE_NOT_SUPPORTED"
    WEIGHT_DTYPE_NOT_SUPPORTED = "WEIGHT_DTYPE_NOT_SUPPORTED"

    # Shared expert gates.
    SHARED_EXPERT_UNSUPPORTED = "SHARED_EXPERT_UNSUPPORTED"
    SHARED_EXPERT_NAMESPACE_UNSUPPORTED = "SHARED_EXPERT_NAMESPACE_UNSUPPORTED"

    # Token identity gates.
    TOKEN_IDENTITY_MISSING_STEP_ID = "TOKEN_IDENTITY_MISSING_STEP_ID"
    TOKEN_IDENTITY_MISSING_POSITIONS = "TOKEN_IDENTITY_MISSING_POSITIONS"
    TOKEN_IDENTITY_MISSING_ORDER_OR_REQUEST = "TOKEN_IDENTITY_MISSING_ORDER_OR_REQUEST"

    # Replay policy gates.
    PARTIAL_REPLAY_DISABLED = "PARTIAL_REPLAY_DISABLED"
    CAST_DISABLED = "CAST_DISABLED"
    DOWNGRADE_DISABLED = "DOWNGRADE_DISABLED"
    POLICY_VIOLATION = "POLICY_VIOLATION"

    # Tape / manifest compatibility gates.
    TAPE_VERSION_MISMATCH = "TAPE_VERSION_MISMATCH"
    TAPE_ABI_VERSION_MISMATCH = "TAPE_ABI_VERSION_MISMATCH"
    TAPE_BACKEND_MISMATCH = "TAPE_BACKEND_MISMATCH"
    TAPE_BACKEND_VERSION_MISMATCH = "TAPE_BACKEND_VERSION_MISMATCH"
    TAPE_MODEL_ARCH_MISMATCH = "TAPE_MODEL_ARCH_MISMATCH"
    TAPE_MODEL_CONFIG_DIGEST_MISMATCH = "TAPE_MODEL_CONFIG_DIGEST_MISMATCH"
    TAPE_REPLAY_LEVEL_MISMATCH = "TAPE_REPLAY_LEVEL_MISMATCH"

    # Record validation codes.
    TOPK_IDX_SHAPE = "TOPK_IDX_SHAPE"
    TOKEN_COUNT_MISMATCH = "TOKEN_COUNT_MISMATCH"
    TOP_K_MISMATCH = "TOP_K_MISMATCH"
    TOP_K_INVALID = "TOP_K_INVALID"
    NUM_EXPERTS_INVALID = "NUM_EXPERTS_INVALID"
    EXPERT_INDEX_NEGATIVE = "EXPERT_INDEX_NEGATIVE"
    EXPERT_INDEX_OUT_OF_RANGE = "EXPERT_INDEX_OUT_OF_RANGE"
    WEIGHTS_MISSING = "WEIGHTS_MISSING"
    WEIGHTS_SHAPE_MISMATCH = "WEIGHTS_SHAPE_MISMATCH"
    WEIGHTS_NOT_FINITE = "WEIGHTS_NOT_FINITE"

    # Compatibility validation codes.
    ABI_VERSION_MISMATCH = "ABI_VERSION_MISMATCH"
    LAYER_ID_MISMATCH = "LAYER_ID_MISMATCH"
    PHASE_MISMATCH = "PHASE_MISMATCH"
    STEP_ID_MISMATCH = "STEP_ID_MISMATCH"
    NUM_EXPERTS_MISMATCH = "NUM_EXPERTS_MISMATCH"
    EXPERT_NAMESPACE_MISMATCH = "EXPERT_NAMESPACE_MISMATCH"
    REQUEST_IDS_MISMATCH = "REQUEST_IDS_MISMATCH"
    SEQUENCE_IDS_MISMATCH = "SEQUENCE_IDS_MISMATCH"
    TOKEN_POSITIONS_MISMATCH = "TOKEN_POSITIONS_MISMATCH"
    BLOCK_IDS_MISMATCH = "BLOCK_IDS_MISMATCH"
    TOKEN_ORDER_MISMATCH = "TOKEN_ORDER_MISMATCH"
    WEIGHTS_REQUIRED_BY_CONTEXT = "WEIGHTS_REQUIRED_BY_CONTEXT"
    WEIGHT_SEMANTICS_MISMATCH = "WEIGHT_SEMANTICS_MISMATCH"
    INDEX_DTYPE_MISMATCH = "INDEX_DTYPE_MISMATCH"
    WEIGHT_DTYPE_MISMATCH = "WEIGHT_DTYPE_MISMATCH"


def normalize_reason_code(code: str | ReplayReasonCode | None) -> str:
    """Return a stable reason-code string, falling back to policy violation."""

    if isinstance(code, ReplayReasonCode):
        return code.value
    if code:
        return str(code)
    return ReplayReasonCode.POLICY_VIOLATION.value
